// Mock data para mascotas (testing)
export const mockPets = [
  {
    id: 1,
    name: 'Luna',
    age: 3,
    breed: 'Gato persa',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=500&fit=crop',
    description: 'Gata tranquila, amorosa y juguetona. Perfecta para apartamentos.',
    gender: 'Hembra',
    location: 'CABA',
    adoptionFee: 1500,
    tags: ['Tranquilo', 'Cariñoso', 'Juguetón'],
  },
  {
    id: 2,
    name: 'Max',
    age: 2,
    breed: 'Perro Labrador',
    image: 'https://images.unsplash.com/photo-1633722715463-d30628519e23?w=400&h=500&fit=crop',
    description: 'Perro energético, leal y excelente con niños. Necesita ejercicio diario.',
    gender: 'Macho',
    location: 'San Isidro',
    adoptionFee: 3000,
    tags: ['Energético', 'Familiar', 'Leal'],
  },
  {
    id: 3,
    name: 'Simba',
    age: 5,
    breed: 'Gato atigrado',
    image: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=400&h=500&fit=crop',
    description: 'Gato adulto, independiente pero cariñoso. Gusta de la tranquilidad.',
    gender: 'Macho',
    location: 'Caballito',
    adoptionFee: 1200,
    tags: ['Independiente', 'Adulto', 'Tranquilo'],
  },
  {
    id: 4,
    name: 'Bella',
    age: 1,
    breed: 'Perro Beagle',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=500&fit=crop',
    description: 'Cachorra adorable, juguetona y muy cariñosa. Ideal para familias activas.',
    gender: 'Hembra',
    location: 'Belgrano',
    adoptionFee: 2500,
    tags: ['Cachorro', 'Juguetón', 'Sociable'],
  },
  {
    id: 5,
    name: 'Misha',
    age: 4,
    breed: 'Gato siamés',
    image: 'https://images.unsplash.com/photo-1606214174585-fe31582dc1d7?w=400&h=500&fit=crop',
    description: 'Gata elegante, muy vocal y exigente de atención. Adora ser el centro.',
    gender: 'Hembra',
    location: 'Recoleta',
    adoptionFee: 1800,
    tags: ['Vocal', 'Demandante', 'Elegante'],
  },
];
